"""Focused exports for the loss-query Hymba character-LM experiments."""

from .data import DEFAULT_CHAR_LM_DATA_PATH, CharVocabulary
from .lm import (
    AlternatingClockTokenFastHymbaCharLM,
    CausalLMOutput,
    ClockConditionedFastHymbaCharLM,
    CurrentClockFusionFastHymbaCharLM,
    EfficientStrictAlternatingClockTokenFastHymbaCharLM,
    EphemeralClockSidecarFastHymbaCharLM,
    FastHymbaCharLM,
    FastHymbaCharLMConfig,
    InterleavedLogitConditionedFastHymbaCharLM,
    IsolatedAlternatingClockTokenFastHymbaCharLM,
    LayerCrossLogitConditionedFastHymbaCharLM,
    LayerCrossTokenLogitConditionedFastHymbaCharLM,
    LogitConditionedFastHymbaCharLM,
    LogitConditionedFastHymbaCharLMConfig,
    LossQueryFastHymbaCharLM,
    MSHymbaCharLM,
    MSHymbaCharLMConfig,
    PreviousClockConditionedFastHymbaCharLM,
    StrictAlternatingClockTokenFastHymbaCharLM,
    TypedIsolatedAlternatingClockTokenFastHymbaCharLM,
    TwoSideHymbaCharLM,
    TwoSideHymbaCharLMConfig,
)
from .training import (
    next_token_accuracy,
    next_token_logits_and_targets,
    next_token_loss,
    weighted_next_token_loss,
)

__all__ = [
    "AlternatingClockTokenFastHymbaCharLM",
    "CausalLMOutput",
    "CharVocabulary",
    "ClockConditionedFastHymbaCharLM",
    "CurrentClockFusionFastHymbaCharLM",
    "DEFAULT_CHAR_LM_DATA_PATH",
    "EfficientStrictAlternatingClockTokenFastHymbaCharLM",
    "EphemeralClockSidecarFastHymbaCharLM",
    "FastHymbaCharLM",
    "FastHymbaCharLMConfig",
    "InterleavedLogitConditionedFastHymbaCharLM",
    "IsolatedAlternatingClockTokenFastHymbaCharLM",
    "LayerCrossLogitConditionedFastHymbaCharLM",
    "LayerCrossTokenLogitConditionedFastHymbaCharLM",
    "LogitConditionedFastHymbaCharLM",
    "LogitConditionedFastHymbaCharLMConfig",
    "LossQueryFastHymbaCharLM",
    "MSHymbaCharLM",
    "MSHymbaCharLMConfig",
    "PreviousClockConditionedFastHymbaCharLM",
    "StrictAlternatingClockTokenFastHymbaCharLM",
    "TypedIsolatedAlternatingClockTokenFastHymbaCharLM",
    "TwoSideHymbaCharLM",
    "TwoSideHymbaCharLMConfig",
    "next_token_accuracy",
    "next_token_logits_and_targets",
    "next_token_loss",
    "weighted_next_token_loss",
]
